### ISSUE TITLE
Rev 1.1 doc bugs

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-docs#318]
- [x] static methods declared as instance methods. e.g. `balanced.APIKey().query` should be `balanced.APIKey.query`
- [x] Authentication section is blank https://docs.balancedpayments.com/1.1/api/authentication/?language=python#authenticating-to-balanced
- [x] static as instance `balanced.BankAccountVerification().find()`
- [x] ~~Charge a bank account should be Debit a bank account https://docs.balancedpayments.com/1.1/api/bank-accounts/?language=python#charge-a-bank-account~~ #324
- [x] ~~params called `xxx_uri` should be `xxx` (no uri)~~ #329
- [x] ~~missing how to associate a bank account to a customer https://docs.balancedpayments.com/1.1/api/bank-accounts/?language=python - i see it's under customer but maybe reciprocate onto the funding instrument section since you're operating on the funding instrument~~ #325
- [ ] List all credits for a bank account maybe should be list all credits for a funding instrument. same deal for debits. 
- [x] ~~no section how to refund a debit - https://docs.balancedpayments.com/1.1/api/debits/?language=python#create-a-debit~~ #326
- [x] ~~no section how to add a transaction to an order - https://docs.balancedpayments.com/1.1/api/orders/?language=python#create-an-order~~ #327
- [x] ~~no overview about orders - https://docs.balancedpayments.com/1.1/api/orders/?language=python~~ #328
